# Generated by Django 5.0.6 on 2024-10-20 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultants', '0003_remove_consultantservice_documents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer')], max_length=50)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_id', models.CharField(max_length=255, unique=True)),
                ('reference_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('initiated', 'Initiated'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_url', models.URLField(blank=True, max_length=255, null=True)),
                ('gateway_id', models.CharField(blank=True, max_length=255, null=True)),
                ('consultant_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='consultants.consultantservice')),
            ],
        ),
    ]
