# Generated by Django 5.0.6 on 2024-10-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantservice',
            name='reference_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
