# Generated by Django 5.0.6 on 2024-10-20 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0002_alter_consultantservice_reference_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultantservice',
            name='documents',
        ),
        migrations.CreateModel(
            name='ConsultantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='consultant_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='consultants.consultantservice')),
            ],
        ),
    ]
