# Generated by Django 5.0.6 on 2024-10-20 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhishingAttackSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_website', models.CharField(blank=True, max_length=100, null=True)),
                ('company_industry', models.CharField(blank=True, max_length=100, null=True)),
                ('user_list', models.FileField(upload_to='user_lists/')),
                ('total_users', models.IntegerField(blank=True, null=True)),
                ('order_status', models.CharField(choices=[('waiting_payment', 'Waiting For Payment'), ('on_going', 'On Going'), ('completed', 'Completed')], default='waiting_payment', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.normaluserinfo')),
            ],
        ),
    ]
